import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const outDir = resolve(root, "dist");

const NAMESPACE: Record<string, string> = {
  color: "color",
  space: "spacing",
  radius: "radius",
  fontSize: "text",
  fontWeight: "font-weight",
};

type Flat = {
  path: string[];
  cssVar: string;
  rawValue: string | number;
  type: string;
  group: string;
  layer: "primitive" | "semantic";
};

function kebab(s: string) {
  return s.replace(/([a-z0-9])([A-Z])/g, "$1-$2").toLowerCase();
}

function flatten(
  node: unknown,
  layer: Flat["layer"],
  path: string[] = [],
  inheritedType?: string,
  out: Flat[] = [],
): Flat[] {
  if (typeof node !== "object" || node === null) return out;
  const obj = node as Record<string, unknown>;
  const type = (obj.$type as string | undefined) ?? inheritedType;

  if ("$value" in obj) {
    const group = path[0]!;
    const ns = NAMESPACE[group];
    if (!ns) throw new Error(`Unknown token group: "${group}"`);
    out.push({
      path,
      cssVar: `--${ns}-${path.slice(1).map(kebab).join("-")}`,
      rawValue: obj.$value as string | number,
      type: type ?? "unknown",
      group,
      layer,
    });
    return out;
  }

  for (const [key, child] of Object.entries(obj)) {
    if (key.startsWith("$")) continue;
    flatten(child, layer, [...path, key], type, out);
  }
  return out;
}

const REF = /\{([^}]+)\}/g;

function buildIndex(tokens: Flat[]) {
  const byPath = new Map<string, Flat>();
  for (const t of tokens) byPath.set(t.path.join("."), t);
  return byPath;
}

function toCssValue(t: Flat, byPath: Map<string, Flat>): string {
  if (typeof t.rawValue !== "string") return String(t.rawValue);
  return t.rawValue.replace(REF, (_, ref: string) => {
    const target = byPath.get(ref);
    if (!target)
      throw new Error(`Unknown reference: {${ref}} (${t.path.join(".")})`);
    return `var(${target.cssVar})`;
  });
}

function resolveLiteral(
  t: Flat,
  byPath: Map<string, Flat>,
  visiting: Set<string> = new Set(),
): string | number {
  const id = t.path.join(".");
  if (visiting.has(id)) {
    throw new Error(`Circular reference: ${[...visiting, id].join(" → ")}`);
  }
  if (typeof t.rawValue !== "string") return t.rawValue;
  visiting.add(id);
  const result = t.rawValue.replace(REF, (_, ref: string) => {
    const target = byPath.get(ref);
    if (!target) throw new Error(`Unknown reference: {${ref}} (${id})`);
    return String(resolveLiteral(target, byPath, visiting));
  });
  visiting.delete(id);
  return result;
}

const primitive = JSON.parse(
  readFileSync(resolve(root, "src/tokens/primitive.json"), "utf8"),
);
const semantic = JSON.parse(
  readFileSync(resolve(root, "src/tokens/semantic.json"), "utf8"),
);

const tokens = [
  ...flatten(primitive, "primitive"),
  ...flatten(semantic, "semantic"),
];
const byPath = buildIndex(tokens);

for (const t of tokens) resolveLiteral(t, byPath);

const isPrimitiveColor = (t: Flat) =>
  t.layer === "primitive" && t.group === "color";
const rootBlock = tokens.filter(isPrimitiveColor);
const themeBlock = tokens.filter((t) => !isPrimitiveColor(t));

const line = (t: Flat) => `  ${t.cssVar}: ${toCssValue(t, byPath)};`;

const css = `/* Generated by @orrery/tokens — do not edit manually. */
:root {
${rootBlock.map(line).join("\n")}
}

@theme inline {
${themeBlock.map(line).join("\n")}
}
`;

const flat = Object.fromEntries(
  tokens.map((t) => [
    t.path.join("."),
    {
      value: resolveLiteral(t, byPath),
      raw: t.rawValue,
      cssVar: t.cssVar,
      type: t.type,
      layer: t.layer,
    },
  ]),
);

const names = tokens.map((t) => t.path.join("."));
const dts = `export type TokenName =
${names.map((n) => `  | ${JSON.stringify(n)}`).join("\n")};

export interface TokenRecord {
  value: string | number;
  raw: string | number;
  cssVar: string;
  type: string;
  layer: "primitive" | "semantic";
}

export declare const tokens: Record<TokenName, TokenRecord>;
export declare function cssVar(name: TokenName): string;
`;

const js = `export const tokens = ${JSON.stringify(flat, null, 2)};
export function cssVar(name) {
  const t = tokens[name];
  if (!t) throw new Error("Unknown token: " + name);
  return \`var(\${t.cssVar})\`;
}
`;

mkdirSync(outDir, { recursive: true });
writeFileSync(resolve(outDir, "theme.css"), css);
writeFileSync(resolve(outDir, "tokens.json"), JSON.stringify(flat, null, 2));
writeFileSync(resolve(outDir, "index.js"), js);
writeFileSync(resolve(outDir, "index.d.ts"), dts);

console.log(
  `✓ ${tokens.length} token → theme.css, tokens.json, index.js, index.d.ts`,
);
